### PR TITLE
added milvus vectorstore support

### PR DESCRIPTION
**Pull request by yushangfu**
added milvus vectorstore support, but need to deploy milvus and embedding model in advance.
I tested it in my env, and everything is ok, please check, thanks

### CODE REVIEW

**Comment by peilongchencc** [comment]
I just needed this, thank you for your contribution!🥰

**Review by zainhoda — APPROVED** [review]

**Comment by xiaofan-luan** [comment]
thanks for the contribution!
really helpful to have this!

**Comment by zc277584121** [comment]
Hi @yushangfu , thanks for your contribution.
I have reviewed your commit, and found there are still some details to be optimized. So I have opened a https://github.com/yushangfu/vanna/pull/1 on the top of this branch, can you please merge my PR and update this current PR, so that my commit will work together :)

**Comment by yushangfu** [comment]
@zc277584121 Hi, Could you please ask @zainhoda to help you review your code? Currently I moved to another project, I have no Milvus env to test your code. Sorry for that

**Comment by zainhoda** [comment]
@zc277584121 feel free to open a new PR from your branch

**Comment by zc277584121** [comment]
@zainhoda https://github.com/vanna-ai/vanna/pull/496
thanks

**Comment by zainhoda** [comment]
Closing in favor of #496

**Pull request closed without merging**
