### PR TITLE
fix: avoid duplicate DDL and question-sql in chromadb

### PR DESCRIPTION
**Pull request by everdark**
A potential patch for https://github.com/vanna-ai/vanna/issues/330

### CODE REVIEW

**Comment by andreped** [comment]
Hmm, this solution would not be backward compatible though. If a user had an existing vector store, updating vanna would mean that duplicates would still occur. Perhaps adding hash IDs for each item is the best solution, but is there something obvious we are missing maybe?

Thoughts, @zainhoda?

**Comment by zainhoda** [comment]
This looks like a pretty reasonable fix -- it will only work for Chroma but there's very little downside in adding this

**Review by zainhoda — APPROVED** [review]

**Comment by andreped** [comment]
@zainhoda Just realized that we did not address documentation duplicates in this PR. This means that we have different behaviour for docs than for SQL and DDL training in the main branch right now:
https://github.com/vanna-ai/vanna/pull/336/files#diff-c1935d21483004aa0c17dc5943337f3448e868df04ee2e31318e745e46138857L87

**Comment by zainhoda** [comment]
@andreped yes -- that's a good point. I'll change that

**Pull request merged**
