### PR TITLE
Adding Google Gemini Chat integration to Vanna

### PR DESCRIPTION
**Pull request by vipgupta**
As a frequent user of Vanna in my projects, I've successfully integrated Google Gemini Chat with Vanna. I believe this integration could be valuable to other users, so I've submitted this pull request to share my work with the community. This addition enables seamless integration of Google Gemini Chat with Vanna (both through API key and Vertex AI), potentially enhancing its functionality for users who require Gemini chat capabilities.

### CODE REVIEW

**Comment by zainhoda** [comment]
@vipgupta awesome! Thank you! I had started playing with Gemini but I couldn't find a good way to get the system prompt in there as it didn't seem like Gemini had an option to set the system prompt.

In this code, it seems like the messages are being flattened to strings and then the prompt is a list of strings without role? This is an interesting approach. I'll check it out. Did you find that it actually works?

**Comment by vipgupta** [comment]
@zainhoda Yes it works! Verified it both with Vertex AI and Google AI studio API key. Yes, Gemini doesn't have a differentiation between a system prompt and a user prompt, and this approach of flattening the messaged worked. We are using it in our project for SQL query generation :)

**Comment by vipgupta** [comment]
@zainhoda Can you review the PR? Also, here's a [thread](https://www.googlecloudcommunity.com/gc/AI-ML/Implementing-System-Prompts-in-Gemini-Pro-for-Chatbot-Creation/m-p/715501) on people complaining about Gemini not having a system prompt and using the flattening out approach.

**Comment by vipgupta** [comment]
Sounds good! Let me know if you need any help from my end.

**Review by zainhoda — APPROVED** [review]

**Pull request merged**
